server:
  port: 8081 #服务端口
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://huran:111111@127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true #将自己的真是Ip注册到服务中
    ip-address: 192.168.10.30
    hostname: 192.168.10.30
spring:
  application:
    name: hr-item
management: # 2.0 手动刷新需要配置
  endpoints:
    web:
      exposure:
        include: "*"