server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
spring:
  security:
    user:
      password: 111111
      name: huran
  application:
    name: hu-eureka