server:
  port: 8083 #服务端口
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://huran:111111@127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true #将自己的真是Ip注册到服务中
    ip-address: 127.0.0.1
spring:
  application:
    name: hr-item #指定服务名称
