server:
  port: 8086 #服务端口
spring:
  application:
    name: hr-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huran111/hr-config-server.git
      username: 1345122890@qq.com
      password: hu13523221836
  rabbitmq:
    password: guest
    username: guest
    virtual-host: /
    host: localhost
eureka:  #注册到Eureka上
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://huran:111111@127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"